-- disable lsp diagnostic for certain file names
-- local disable_lsp_group = vim.api.nvim_create_augroup("DisableLsp", { clear = true })
-- vim.api.nvim_create_autocmd("BufCreate", {
--   group = disable_lsp_group,
--   pattern = { ".env*" },
--   callback = function(event)
--     local lsp_clients = vim.lsp.get_clients { bufnr = event.buf }
--     for _, client in ipairs(lsp_clients) do
--       vim.notify("Detaching " .. client.name .. " from " .. event.buf)
--       vim.lsp.buf_detach_client(event.buf, client.id)
--     end
--     vim.diagnostic.disable(event.buf)
--   end,
-- })
