require "custom.autocmd.autoreload"
require "custom.autocmd.comment"
require "custom.autocmd.disable-fold"
require "custom.autocmd.disable-lsp"
require "custom.autocmd.persistence"
require "custom.autocmd.vhelp"
require "custom.autocmd.relative-line"
-- require "custom.autocmd.input-method"
