require "config.opts"
require "config.autocmd"
require "config.condition"
require "config.lazy"
require "config.usercmd"
require "config.keymaps"
require "config.filetype"
require "config.highlights"
