local opts = {
  ensure_installed = {
    "lua-language-server",
    "bash-language-server",
    "beautysh",
    "black",
    "clang-format",
    "clangd",
    "cmake-language-server",
    "cmakelang",
    "cmakelint",
    "codelldb",
    "codespell",
    "css-lsp",
    "dockerfile-language-server",
    "eslint-lsp",
    "html-lsp",
    "isort",
    "json-lsp",
    "luaformatter",
    "mypy",
    "markdownlint",
    "nginx-language-server",
    "pyright",
    "rust-analyzer",
    "shellcheck",
    "stylua",
    "svelte-language-server",
    "tailwindcss-language-server",
    "typescript-language-server",
    "typst-lsp",
    "yaml-language-server",
  },
}

return opts
