local opts = {
  ensure_installed = {
    "lua-language-server",
    "bash-language-server",
    "black",
    "clang-format",
    "clangd",
    "cmake-language-server",
    "cmakelang",
    "cpptools",
    "cspell",
    "css-lsp",
    "docker-compose-language-service",
    "dockerfile-language-server",
    "eslint-lsp",
    "eslint_d",
    "html-lsp",
    "isort",
    "json-lsp",
    "luaformatter",
    "mypy",
    "markdownlint",
    "nginx-language-server",
    "prettier",
    "prettierd",
    "pyright",
    "ruff",
    "shellcheck",
    "stylua",
    "svelte-language-server",
    "tailwindcss-language-server",
    "typescript-language-server",
    "typst-lsp",
    "yaml-language-server",
    "yamlfmt",
  },
}
return opts
